# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Weather Forecast MCP Server
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Ensure environment variables have defaults (can be overridden at runtime)
ENV OPENWEATHER_API_KEY=6b2e97b1b6559436aee37b83b71412b3
ENV DEFAULT_UNITS=metric
ENV LANGUAGE=tr

# Use unbuffered output
ENV PYTHONUNBUFFERED=1

# Launch the MCP server via stdio transport
CMD ["python", "server.py"]
